How to write cleaner, faster, and more efficient python code.

* First, efficient code is fasta and has a small latency between execution and returninng a result.
* Second, efficent code allociates resuource skillfully and isn't subjected to unnecessary overhead.

Although your defination of fast runtime and small memory usage may depend on the task.


**Non-Pythonic:**
```python
double_numbers = []
for i in range (len(numbers)):
doubled_number.append(number[i]*2)
```


**Pythonic:** The code you write follows the best practices and guiding principle of python.
Pythonic code tends to be less verbose and easier to interpret.
```python
doubled_number = [x*2 for x in numbers]
```

#### The zen of Python by Tin Peters:
Enter zen of Python: Here is a list of a few idioms and best practices that summarize Python's degin philosophy.

* Beautiful is better than ugly.
* Explicit is better than implicit.
* Complex is better than Complicated.
* Flat is better than Nested.
* Sparse is better than Dense.
* Readability counts.
* Special case aren't special enough to break the rules.
* Although practically beats purity.
* Errors should never pass silently.
* Unless explictly silenced.
* In the face of ambiguity, refuse the temptation to guess.


##### Building with builtins:

Built-in components are reffered to as the Python Standard Library.

###### Built-in Types:
* List
* Tuple
* Set
* Dict and others

###### Built-in Functions:
* print()
* len ()
* range()
* round()
* enumurate()
* map()
* zip() and others.

###### Built-in Modules:
* os
* sys
* itertools
* Collections
* math and others

#### range():

Ecplicitly typing a list of numbers.

In [1]:
nums = [0,1,2,3,4,5,6,7,8,9,10]
print(nums)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Insted, let's use range to accomplish this task.

In [2]:
# range(start,stop)
nums = range(0,11)
num_list = list(nums)
print(num_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [3]:
# range(stop)
nums = range(11)
num_list = list(nums)
print(num_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
# range(start, stop, step-vale)
even_nums = range(2,11,2)
even_nums_list = list(even_nums)
print(even_nums_list)

[2, 4, 6, 8, 10]


Exercise: 
1. Create a sequence of numbers from 0 to a stop value (which is exclusive). This is useful when you want to create a simple sequence of numbers starting at zero:

2. Create a sequence of numbers from a start value to a stop value (which is exclusive) with a step size. This is useful when you want to create a sequence of numbers that increments by some value other than one. For example, a list of even numbers:


In [5]:
# Create a range object that goes from 0 to 5.
nums = range(0,6)
print(type(nums))

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Creating new list of odd numbers from 1 to 11 by unpacking range object.
num_list2 = [* range(1,11,2)]  # Unpack range object using the star character(*)
print(num_list2)

<class 'range'>
[0, 1, 2, 3, 4, 5]
[1, 3, 5, 7, 9]


#### enumurate()

Enumurate creates an index item pair for each item in the object provided. 
For example, calling enumurate on the list below provides a sequence of indexed value.

In [6]:
# Creates an indexed list of objects:
letters = ['a','b','c','d']
indexed_list = enumerate(letters)
indexed_letters_list = list(indexed_list)
print(indexed_letters_list)

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]


Similar to range, enumerate return an enumerate object, which can also be convered into list and printed. We can also specify the starting index of enumerate with the keyword argument start.

In [7]:
letters = ['a','b','c','d']
indexed_list = enumerate(letters,start =5)
indexed_letters_list = list(indexed_list)
print(indexed_letters_list)

[(5, 'a'), (6, 'b'), (7, 'c'), (8, 'd')]


Here, we tell enumerate to start the incex at five by passing start equals five into the function call.

**Exercise: suppose you had a list of people that arrived at a party you are hosting. The list is ordered by arrival (Jerry was the first to arrive, followed by Kramer, etc.):**

names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

If you wanted to attach an index representing a person's arrival order, you could use the following for loop:
```python
indexed_names = []
for i in range(len(names)):
    index_name = (i, names[i])
    indexed_names.append(index_name)

[(0,'Jerry'),(1,'Kramer'),(2,'Elaine'),(3,'George'),(4,'Newman')]
```

But, that's not the most efficient solution. Let's explore how to use enumerate() to make this more efficient.

In [8]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']
# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name)
print(indexed_names)

# Rewrite the above for loop using List Comprehension.
indexed_names =[(i,name) for i, name in enumerate(names)]
print(indexed_names)

# Unpack an enumerate object with a string index of one
indexed_names_unpack = [* enumerate(names,1)]


[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]


#### map()

map applies a function to each element in an object. Notice that map takes two arguments: first, the function you'd like to apply and the second, the object you'd like to apply that function on.

In [9]:
nums = [1.5, 2.3, 3.4, 4.6, 5.0]
rnd_nums = map(round, nums)
print(list(rnd_nums))

[2, 2, 3, 5, 5]


Here, we use map to apply the built-in function round to each element of the nums list. 

map can also be used with  a lambda or an anonymous function.

In [10]:
nums = [1,2,3,4,5]
sqrd_nums = map(lambda x: x **2, nums)
print(list(sqrd_nums))

[1, 4, 9, 16, 25]


Here, we use map and lambda expression to apply a funcion, which defined on the fly, to our origional list nums.

The map function provides quick and clean way to apply a function to an object iteratively without writing a for loop.

**Exercise: using Python's built-in map() function to apply a function to every element of an object. Let's look at a list of party guests:**
```python 
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']
```
Suppose you wanted to create a new list (called names_uppercase) that converted all the letters in each name to uppercase. you could accomplish this with the below for loop:
```python
names_uppercase = []

for name in names:
  names_uppercase.append(name.upper())

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']
```
Let's explore using the map() function to do this more efficiently in one line of code.


In [11]:
names = ['Jerry','Kramer','Elaine','George','Newman']
# Use map to apply str.upper to each element in names
names_map = map(str.upper,names)
# Print the type of the names_map 
print(type(names_map))
# Unpack names_map into a list
names_uppercase =[list(names_map)]
# Print the list created
print(names_uppercase)


<class 'map'>
[['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']]


### Power of Numpy:
It is the fundamental package for Scientific Computing in python and provides a number of benifits for writing efficent code. Numpy array provide a fast and memory efficient alternative to Python list.

In [12]:
num_list = list(range(5))
print(num_list)

[0, 1, 2, 3, 4]


In [13]:
import numpy as np
num_list = np.array(range(5))
print(num_list)

[0 1 2 3 4]


Numpy arrays are homogeneous, which means that they must contain elements of the same type.

In [14]:
# Numpy array homogenity
num_np_ints = np.array([1,2,3])
print(num_np_ints)
print(num_np_ints.dtype)

[1 2 3]
int32


Numpy convert the integers to float to retain that array's homegoneous nature. Homogeneity allow NumPy array to be more memory efficient and faster than Python lists.

In [15]:
num_np_floats = np.array([1,2.4,8])
print(num_np_floats)
print(num_np_floats.dtype)

[1.  2.4 8. ]
float64


##### NumPy array broadcasting:
Broadcasting refers to a numpy array's ability to vectorize operations, so they are performed on all elements of an object at once.

Let's square the values using  a list by writing a for loop or using a list comprehension.

In [16]:
nums = [-2,-1,0,1,2]
sqrd_nums = []
for num in nums:
    sqrd_nums.append(num ** 2)
print(sqrd_nums)

[4, 1, 0, 1, 4]


In [17]:
sqrd_nums = [num ** 2 for num in nums]
print(sqrd_nums)

[4, 1, 0, 1, 4]


But neither of this approches is the most efficient way of doing this. Here lies the second advantage of NumPy arrays, there broadcasting functionality.

In [18]:
num_np = np.array([-2,-1,0,1,2])
num_np ** 2

array([4, 1, 0, 1, 4])

NumPy array vectorize operations, so they are performed on all elements of an object at once. This allows us to efficiently perfor calcualtions over entire arrays.

#### NumPy array boolean indexing:
NumPy arrays also have a special technique called boolean indexing. Suppose we wanted to gather onlu positive numbers from the sequence listed here.

In [19]:
nums = [-2,-1,0,1,2]
nums_np = np.array(nums)

In [20]:
num_np >0 

array([False, False, False,  True,  True])

With an array we can create a boolean mask using a simple inequality. Indexing the array is as simple as enclosing this inequality in square brackets.

In [21]:
num_np[num_np>0]

array([1, 2])

To do this using a list, we need to write a for loop to filter the list or use a list comprehension.

In [22]:
# for loop (inefficient option)
pos = []
for num in nums:
    if num>0:
        pos.append(num)
print (pos)

# using list comprehension
pos = [ num for num in nums if num > 0]
print(pos)

[1, 2]
[1, 2]


Either in this case , using NumPy array to index is less verbose and has a faster runtime.

In [23]:
# 2-d NumPy array.
nums = np.array([[ 1,  2,  3,  4,  5],[6,  7, 8,  9, 10]])
# Print second row of nums
print(nums[1,:])

# Print all the elements of the nums that are greater than six
print(nums[nums>6])

# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

# Replace the third column of nums
nums[:,2] = nums[:,2]+1
print(nums)

[ 6  7  8  9 10]
[ 7  8  9 10]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


**When compared to a list object, what are two advantages of using a numpy array?**

Ans: 
A numpy array contains homogeneous data types (which reduces memory consumption) and provides the ability to apply operations on all elements through broadcasting.

#### Exercise: 
You have a list of guests (the names list). Each guest, for whatever reason, has decided to show up to the party in 10-minute increments. For example, Jerry shows up to Festivus 10 minutes into the party's start time, Kramer shows up 20 minutes into the party, and so on and so forth.

We want to write a few simple lines of code, using the built-ins we have covered, to welcome each of your guests and let them know how many minutes late they are to your party. Note that numpy has been imported into your session as np and the names list has been loaded as well.

In [24]:
# Create a list of arrival time 
arrival_time = [* range(10,51,10)]
print(arrival_time)


[10, 20, 30, 40, 50]


You realize your clock is three minutes fast. Convert the arrival_times list into a numpy array (called arrival_times_np) and use NumPy broadcasting to subtract three minutes from each arrival time.

In [25]:
# Conver the arrival_times to an array and update the time.
arrival_time_np = np.array(arrival_time)
new_time = arrival_time_np - 3
print(new_time)

[ 7 17 27 37 47]


Use list comprehension with enumerate() to pair each guest in the names list to their updated arrival time in the new_times array. You'll need to use the index variable created from using enumerate() on new_times to index the names list.

In [26]:
# name of the guests
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

# Create a list of arrival times
arrival_time = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_time_np = np.array(arrival_time)
new_time = arrival_time_np - 3

# Use list comprehension and enumurate to pair guests to new times.
guest_arrivals = [(names[i], time) for i, time in enumerate(new_time)]
print(guest_arrivals)

[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


#### Examining runtime
In this section we will examine the runtime of hte code. runtime is an important consideration when thinking about the efficiency. Comparing runtimes between two code bases, that are effectively do the same thing, allows us to pick the code with the optimal performance. By gathering and analyzing runtimes, we can be sure to implement the code that is fastest and thus more efficient.

To compare runtimes, we need to be able to compute the runtime for  a line or multiple lines of code. **IPython** comes with some built-in magic commands we can use to time our code. Magic commands are enhancements that has been added on the top of the normal Python syntax. These commands are prefixed with the percentage sign.

##### Using %timeit

Consider this example: we want to inspect the runtime for selecting 1000 random numbers between zero and one using NumPy's random.rand() function. Using %timeit just requires adding the magic command before the line of code we want to analyze. That's it! One simple command to gather runtimes. Magic indeed!

In [27]:
import numpy as np
rand_nums = np.random.rand(1000)
%timeit rand_nums = np.random.rand(1000)

7.42 µs ± 135 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


One advantage to using %timeit is the fact that it provides an average of timing statistics. Notice that the output provides a mean, and standard deviation, of time.

We also see that multiple runs and loops were generated. %timeit runs through the provided code multiple times to estimate the code's execution time. This provides a more accurate representation of the actual runtime rather than relying on just one iteration to calculate the runtime. The mean and standard deviation displayed in the output is a summary of the runtime considering each of the multiple runs.

The number of runs (-r) and/or (-n) represents how many iterations you'd like to use to estimate the runtime. The number of loops represents how many times you'd like the code to be executed per run. We can specify the number of runs, using the -r flag, and the number of loops, using the -n flag. Here, we use -r2, to set the number of runs to two and -n10, to set the number of loops to ten. In this example, %timeit would execute our random number selection 20 times in order to estimate runtime (2 runs each with 10 executions).

In [28]:
# Set the number of runs to 2 (-2r)
# set number of loops to 10 (-n10)
%timeit -r2 -n10 rand_nums = np.random.randint(1000)

6.17 µs ± 3.28 µs per loop (mean ± std. dev. of 2 runs, 10 loops each)


##### Using %timeit in line magic mode: 
Another cool feature of %timeit is its ability to run on single or multiple lines of code. When using %timeit in line magic mode, or with a single line of code, one percentage sign is used.


In [29]:
%%timeit 
nums = []
for x in range(10):
    nums.append(x)

600 ns ± 5.79 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


##### Saving output:
We can save the output of %timeit into a variable using the -o flag. This allows us to dig deeper into the output and see things like the time for each run, the best time for all runs, and the worst time for all runs. Let's try using %timeit with some of Python's built-in data structures.

In [30]:
times = %timeit -o rand_nums = np.random.rand(1000)

7.24 µs ± 45.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [31]:
# time for each runs
times.timings

[7.257818999933079e-06,
 7.216205999720842e-06,
 7.250455999746918e-06,
 7.286069999681786e-06,
 7.272370999562554e-06,
 7.1414729999378325e-06,
 7.2611909999977795e-06]

In [32]:
# best time for all runs
times.best

7.1414729999378325e-06

In [33]:
# worst time for all runs 
times.worst

7.286069999681786e-06

##### Comparint times:
Python's built-in data structures called lists, dictionaries, and tuples. Python allows us to create these data structures using either a formal name, like list, dict, and tuple spelled out, or a shorthand called literal syntax. If we wanted to compare the runtime between creating a dictionary using the formal name and creating a dictionary using the literal syntax, we could save the output of the individual %timeit commands as shown here. Then, we could compare the two outputs.

In [34]:
# Python data structures can be created using formal name
formal_list = list()
formal_dict = dict()
formal_tuple = tuple()

# Python data structures can be created using literal syntax
literal_list = []
literal_dict = {}
literal_tuple = ()

If we wanted to compare the runtime between creating a dictionary using the formal name and creating a dictionary using the literal syntax, we could save the output of the individual %timeit commands as shown here. Then, we could compare the two outputs.

In [35]:
f_time = %timeit -o formal_dict = dict()

65.5 ns ± 0.278 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [36]:
l_time = %timeit -o literal_dict = {}

21.6 ns ± 0.253 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


For simplicity, let's look at just the output of both the %timeit commands to see which was faster. Here, we can see that using the literal syntax to create a dictionary is faster than using the formal name.

Reference table of time orders of magnitude is provided below.
<table>
    <tr>
        <th> Symbol </th>
        <th>Name </th>
        <th> Unit(s) </th>
    </tr>
    <tr>
        <td>ns</td>
        <td>namosecond</td>
        <td>10^-2</td>
    </tr> 
    <tr>
        <td> \mu </td>    